services:
  web:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0
    ports:
    - 7900:8000

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ecommerce_user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=ecommerce_db


volumes:
  postgres_data: